#!/usr/bin/env ruby

require_relative './fnsserver.rb'

#Initialize globle parameter
$fns_queue  =   SizedQueue.new(100)
$fns_log    =   SizedQueue.new(100)
$fns_path   =   "."

if ARGV[0]
  path = ARGV[0]
else
  p "Useage:[File Paht] [Repeat(max 48)] [Host_Ip(deafult localhost)]"
  return
end

if ARGV[1]
  repeat = ARGV[1].to_i
  repeat = 48 if repeat > 48
else
  repeat = 0
end

host_ip = "localhost"
if ARGV[2]
  size = ARGV[2].to_i
else
  size = 0
end

msg = Hash.new
msg["Subject"]    =   "Dummy Article"
msg["From"]       =   "xiaokunyao <xiaokunyao@softlab>"
msg["Tags"]       =   "all"
msg["User-Agent"] =   "dummy maker" 

file = File.read(path)
str = file
while size > 0
  str += file
  size -= 1
end
msg["Body"]       =   str

client = FriendNews::FNS_Client.new(11119)
client.connect(host_ip)

while repeat >= 0
  stat_code = client.post(msg)
  puts stat_code
  repeat -= 1
end
